### ISSUE TITLE
New GUI Bugs ? and observations

### ISSUE THREAD

**Issue by LazzaAU** [project-alice-assistant/ProjectAlice#369] opened 2021-01-23 04:29 UTC
Here is a collection of Bugs and observations found with the new merged GUI. Using firefox on Ubuntu with a RPI3b+ and respeaker 4.

PS: This is not me purposely trying to look for faults, i just happened to have several hours where i could poke and prod :)

**Install Issues**

<details>
  <summary>Click to expand solved</summary>

- [x] jsmin, htmlmin and cssmin don't install on their own and need manually installed 

```./venv/bin/pip3 install htmlmin```

```./venv/bin/pip3 install cssmin```

``` ./venv/bin/pip3 install jsmin```

- [x] nginx needs installed manually 

``` sudo apt-get update ```

``` sudo apt-get install nginx ```

**any skill that is causing error , remove it for now untill the skill gets its code updated.**

- [x] MqttManager.py was not the correct one. (in process of being fixed ? )

 ```git pull```

 should be fixed by the time people read this

then restart Alice and potentially she should open on 
http:<Alice Ip>:5000 as per normal

</details>

**Display Issues**

<details>
  <summary>Click to expand solved</summary>

- [x] Widget screen displays this on Firefox with Dark theme enabled
![widget](https://user-images.githubusercontent.com/31381872/105556392-fe00ca00-5d55-11eb-93da-8ea4123fef2c.gif)

- [x] And similar results with instructions.

![Kazam_screenshot_00002](https://user-images.githubusercontent.com/31381872/105568099-990f9900-5d82-11eb-8514-81c757519ea0.png)

- [x] Internet Quality slider and wakeword sensitivity  slider no longer display's the "number" of your current setting, 

- [x] syslog screen goes black if i refresh the page, no broken heart to indicate that Alice is dead. Assume that's a expected outcome ?

- [x] Downloading a skill from the store then returning to the skills list wont reflect the new skill until page is refreshed. Assume this is expected result but just mentioning :)

- [x] found another display quirk in telemetry skill - cant scroll it, half the view is there, unable to access a save button
![Kazam_screenshot_00003](https://user-images.githubusercontent.com/31381872/105624920-1ca7b380-5e71-11eb-870d-1f26cd803e86.png)

- [x] Very minor item ....dialogView screen - suggest changing the input box border colour ? on a dark theme the only thing you see is the arrow and a very faint border around the input box.. sit outside like i do often and you don't see the border at all :)

</details>

- [x] Miss Aligned text in admin screen - firefox - ubuntu
![missAlignedtext](https://user-images.githubusercontent.com/31381872/105556890-b62e7280-5d56-11eb-8c72-eaf49225012f.png)
![Kazam_screenshot_00001](https://user-images.githubusercontent.com/31381872/105565964-44195600-5d75-11eb-99f9-c612f62c272d.png)

**My Home**

<details>
  <summary>Click to expand solved</summary>

- [x] Myhome view zooms out when you scroll down the admin page. refer screen shot posted in #dev https://discord.com/channels/579345007518154752/579365888030015500/804149553552424990
</details>

- [x] Not sure how i've managed it yet but i've managed to make certain devices (like Alice) and some locations disappear. Reloading doesnt fix it. zoom can't find them. trying to re add them says they already exist. (will continue to try and narrow down how this happens)  --> Assumption by Philipp: they are way of the screen - possibly be cause of fixed errors with nested locations. Closing this bulletpoint until it happens again!

**LOG ERRORS**
<details>
  <summary>Click to expand solved</summary>
- [x]  ```File "/home/pi/ProjectAlice/core/base/model/ProjectAliceObject.py", line 117, in broadcast
    func(**kwargs)
  File "/home/pi/ProjectAlice/core/util/AliceWatchManager.py", line 90, in onHotwordToggleOff
    'text': f'Was asked to toggle itself **off** on device **{self.DeviceManager.getDevice(uid=siteId).displayName}**',
AttributeError: 'NoneType' object has no attribute 'displayName' ```

Also get similar with the below 

```Jan 23 13:00:00 TestAlice python[13507]:   File "/home/pi/ProjectAlice/core/base/model/ProjectAliceObject.py", line 100, in broadcast
Jan 23 13:00:00 TestAlice python[13507]:     func(**kwargs)
Jan 23 13:00:00 TestAlice python[13507]:   File "/home/pi/ProjectAlice/core/dialog/DialogManager.py", line 59, in onHotword
Jan 23 13:00:00 TestAlice python[13507]:     self.logDebug(f'Wakeword detected by **{self.DeviceManager.getDevice(uid=siteId).displayName}**')
Jan 23 13:00:00 TestAlice python[13507]: AttributeError: 'NoneType' object has no attribute 'displayName'
```
- [x] **Get this error when trying to save admin screen. Happens in both ASR and TTS saving.**
**UPDATED COMMENT** - The trigger for this is restarting Alice with the admin screen open and not refreshing the page first :)

```
[ConfigManager]           Trying to get config aliceIp but it does not exist
[ConfigManager]           Was asked to update aliceIp but key doesn't exist
[UtilsApi]                Updating config failed for aliceIp: None
Traceback (most recent call last):
  File "/home/pi/ProjectAlice/core/webApi/model/UtilsApi.py", line 79, in setConfig
    self.ConfigManager.updateAliceConfiguration(conf, value, False)
  File "/home/pi/ProjectAlice/core/base/ConfigManager.py", line 214, in updateAliceConfiguration
    raise ConfigurationUpdateFailed()
core.ProjectAliceExceptions.ConfigurationUpdateFailed: None
[ConfigManager]           Trying to get config aliceVersion but it does not exist
[ConfigManager]           Was asked to update aliceVersion but key doesn't exist
[UtilsApi]                Updating config failed for aliceVersion: None
Traceback (most recent call last):
  File "/home/pi/ProjectAlice/core/webApi/model/UtilsApi.py", line 79, in setConfig
    self.ConfigManager.updateAliceConfiguration(conf, value, False)
  File "/home/pi/ProjectAlice/core/base/ConfigManager.py", line 214, in updateAliceConfiguration
    raise ConfigurationUpdateFailed()
core.ProjectAliceExceptions.ConfigurationUpdateFailed: None

</details>


```
**NOTE: Have not tested skills and widgets properly until they are all active. Also un able to test voice related stuff due to the displayName error above. Telemetry graph also not tested

**Comment by Psychokiller1888** [comment] 2021-01-23 08:59
Skills are reactive, they do appear as installed once Alice has confirmed.

Technically, forget about refreshing, it's a single page app

Re theme, that's, cannot repro as I never use the browser's "turn into dark mode" feature as it brings all these issues

**Comment by philipp2310** [comment] 2021-01-25 22:25
- [ ] MyHome: Links show over the menu
![image.png](https://images.zenhubusercontent.com/5f515779be05344e0b2e027e/ed3d9857-b38d-4b63-bfd5-fb4be40792ed)

**Comment by Psychokiller1888** [comment] 2021-01-26 06:40
As a quick morning answer :)
- PairingDone calls saveToDB that calls publishDevice, should update the device on UI, gotta check why not
- Links over menu, yep, saw that, also goes over the header. Very hard to fix
- Device settings scrolling, maybe missing a top container to allow the flex to scroll

**Comment by Psychokiller1888** [comment] 2021-01-26 06:43
Just to confirm, yes, device settings can be dropped in definition of the device, but to clarify, settings control the display value, such as X, Y, Z, W, H, R. The config templates are for the `configs`

**Comment by LazzaAU** [comment] 2021-01-27 02:52
not sure if this is the same as phillips  "maybe hide device links to the parent location" ?

but when you add ( in my case, 49 devices automatically) and they all end up in the hive by default, then you move them to another location you stay linked to the hive and manually have to click unlink, click icon, click the hive, unclick the unlink icon" then repeat... thats a hell of alot of clicking for 49 devices :) 

So i suggest as per previous version, if you move a device to another room, that room becomes parentLocation and the previous room IS NOT automatically linked. That's a user choice.

[ ] - done
[ ] - Not going to implement

**Comment by LazzaAU** [comment] 2021-02-02 04:26
Appears that since the icon changing ability in my home, that 

- [ ] Adding a device link no longer works ?

- [ ] Clicking a device that is NOT a UID of -1 and has a heartbeat, invokes the " Please pair this device" event

- [ ] Shifting a device from a location that has a "parentLocation" will cause the icon to get given a coordinate value of  negative something, EG: { "x" : -49567, "y" -49321....  } which in return puts it miles off the screen.

- [ ] Suggest the notification pop up in "my home" becomes **"notification.success"** instead of notifications.successes.  Successes would be if your referring to the update outcome of ALL devices" success referring to the single device your attempting to update ?. In actual fact a failure is not a success at all so maybe notification.result or something :)... minor detail :) 

non linking screenshot
![NoLinking](https://user-images.githubusercontent.com/31381872/106552109-645dc780-6562-11eb-902a-7cdd5725e68d.gif)

**Comment by Psychokiller1888** [comment] 2021-02-02 07:46
When you hover rooms, you get a red outline and hashed locations, which means linking to that loc is not possible ;)

**Comment by LazzaAU** [comment] 2021-02-20 10:25
Request with Telemetry tab

I know phil calls it a "concept" but i like the telemetry tab and use it often for monitoring battery levels and tank levels. etc

however couple of small requests if you agree :)

- [ ]  Can you please make the telemetry Screen scrollable. Or alternatvely able to expand / collapse the buttons and filters area so the graph takes up the screen space. Currently i have to tab at a guess 12 or so  times to view the full graph
 
 - [ ] We all like color in our life, however personally i think the bright blue of the listed sensors in the filter boxes with the smaller white  text is a bit hard to read and suggest more of a contrasting color scheme for those list of sensors, like a darker shade of blue or something  with a brighter text maybe ?
 
![Kazam_screenshot_00022](https://user-images.githubusercontent.com/31381872/108592450-a340a980-73b9-11eb-937e-430b3be2f9d6.png)
 ?

**Comment by philipp2310** [comment] 2021-06-03 02:50
Summary of open points:
- [ ] Miss Aligned text in admin screen - firefox - ubuntu --> See first post
No firefox/ubuntu available at the moment, can't reproduce.
- [ ] widgets don't seem to use the "main" skillInstance but a cached one (onUpdate changes a different instance that affects Voice, but not widget)
- [ ] Telemetry screen is not scrollable or resizing in a good way

**Comment by philipp2310** [comment] 2021-06-08 22:38
closing this issue - moving the remaining two open points to a better place ;) => #360

**Closed by philipp2310** 2021-06-08 22:38 UTC
Labels: GUI, bug
